orientation_covariance: [0.01,  0.0,   0.0,
                        0.0,   0.01,  0.0,
                        0.0,   0.0,   0.01]
angular_velocity_covariance: [0.01,  0.0,   0.0,
                     0.0,   0.01,  0.0,
                     0.0,   0.0,   0.01]
# For some reason the linear acceleration covariance is changed from 0.01 to 1.0
linear_acceleration_covariance: [1.0,  0.0,   0.0,
                      0.0,   1.0,  0.0,
                      0.0,   0.0,   1.0]
magnetic_covariance: [0.01,  0.0,   0.0,
                     0.0,   0.01,  0.0,
                     0.0,   0.0,   0.01]
